#!/usr/bin/env bash
MIN_ARGS=3

if [ $# -lt $MIN_ARGS ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    if [ "$4" == "" ]; then
	scp $1 $3@$2:~/
    else
	scp -i $4 $1 $3@$2:~/
    fi
fi
