#!/usr/bin/env bash
# script that via SCP send files to remote server
# 4 parameters
# $1 local file path
# $2 remote server ip
# $3 remote user
# $4 path of the key
# if less than 3 parameters
PERROR="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
if [ "$#" -eq "4" ]
then
    scp -o StrictHostKeyChecking=no IdentityFile="$4" "$1" "$3"@"$2":
    exit 0
else
    echo "$PERROR"
    exit 1
fi
