#!/usr/bin/env bash
# Script that install nginx web server

sudo apt-get -y update && sudo apt-get -y upgrade

sudo apt-get install -y nginx
nginx -v

echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
