#!/usr/bin/env bash
# Script that install nginx web server

sudo apt-get -y update && sudo apt-get -y upgrade

sudo apt-get install -y nginx
nginx -v

sudo ufw allow 'OpenSSH' && sudo ufw allow 'Nginx HTTP'
sudo ufw enable

echo "Holberton School" >> /var/www/html/index.nginx-debian.html
service nginx start
