#!/usr/bin/env bash
# fizzbuzz
for i in {1..100}; do
    mod3=$((i % 3))
    mod5=$((i % 5))
    if [ $mod3 -eq 0 ] && [ $mod5 -eq 0 ];then
	echo "FizzBuzz"
    elif [ $mod3 -eq 0 ]; then
	echo "Fizz"
    elif [ $mod5 -eq 0 ]; then
	echo "Buzz"
    else
	echo $i
    fi
done
