#!/usr/bin/env bash
# This script is displaying numbers 1 to 20 and bad luck depend from country

v=1
while [[ $v -le 20 ]]; do
    echo $v
    case $v in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    v=$((v + 1))
done
