#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2 | facebook.com resolves to 8.8.8.8
cp /etc/hosts ./
sed -i s/127.0.0.1/127.0.0.2/ hosts
sed -i s/157.240.11.35/8.8.8.8/ hosts
cp -f host /etc/hosts
